/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

interface OHOS.FileManagement.Backup.IExtension{
    [ipccode 1] void GetFileHandleWithUniqueFd([in] String fileName, [out] int getFileHandleErrCode, [out] FileDescriptor fd);
    [ipccode 2] void HandleClear();
    [ipccode 3] void HandleBackup([in] boolean isClearData);
    [ipccode 4] void PublishFile([in] String fileName);
    [ipccode 5] void HandleRestore([in] boolean isClearData);
    [ipccode 6] void GetIncrementalFileHandle([in] String fileName,
                                              [out] FileDescriptor fd, [out] FileDescriptor reportFd, [out] int errCode);
    [ipccode 7] void PublishIncrementalFile([in] String fileName);
    [ipccode 8] void HandleIncrementalBackup([in] FileDescriptor incrementalFd, [in] FileDescriptor manifestFd);
    [ipccode 9] void IncrementalOnBackup([in] boolean isClearData);
    [ipccode 10] void GetIncrementalBackupFileHandle([out] FileDescriptor fd, [out] FileDescriptor reportFd);
    [ipccode 11] void GetBackupInfo([out] String getBackupInfoResult);
    [ipccode 12] void UpdateFdSendRate([in] String bundleName, [in] int sendRate);
    [ipccode 13] void User0OnBackup();
    [ipccode 14] void UpdateDfxInfo([in] long uniqId, [in] unsigned int extConnectSpend, [in] String bundleName);
    [ipccode 15] void CleanBundleTempDir();
}